spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.170.49.191:5432/lms?currentSchema=sample_dev
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        jdbc.batch_size: 50
        type: trace
        order_inserts: true
        order_update: true
  jackson:
    serialization:
      indent-output: true
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 256MB
      enabled: false
server:
  servlet-path: /*
  address: localhost
  port: 8088
security:
  ignored: /**
  lms-key: Password1!
logging:
  path: /weblogs/eap/domain
  file: ${logging.path}/demo.log
  level:
    ROOT: ERROR
    com.prudential.lms: DEBUG
    org.springframework:
      web: DEBUG
      data: INFO
    org.hibernate: ERROR